name: Survival
version: '${project.version}'
main: me.hotpocket.survival.Survival
api-version: 1.18
authors: [ hotpocket, Lord, Catalysm ]
commands:
  gma:
    description: Sets the gamemode of a player to adventure.
  gmc:
    description: Sets the gamemode of a player to creative.
  gms:
    description: Sets the gamemode of a player to survival.
  gmsp:
    description: Sets the gamemode of a player to spectator.
  day:
    description: Sets the time on the server to day (1000 ticks).
  night:
    description: Sets the time on the server to night (13000 ticks).